name: pasanaku-metadata

plugins:
  - name: solidity
  - name: foundry
  - name: etherscan
  - name: arbitrum

solidity:
  via_ir: true

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.6.1


solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelinSolidity/5.6.1"